/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 * Update: Edited to be used in ARM CPU MODES lecture.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "core_cm3.h"

#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_EXTI_driver.h"
#include "stm32f103c6.h"
#include "Lcd.h"
#include "KPD_interface.h"

#include "Schedular.h"

#include "string.h"


// Remember the modifications in the linkersript



Task_Config Task1, Task2, Task3;


void task1()
{
	while(1){
		// Task1 Code
	}
}

void task2()
{
	while(1){
		// Task1 Code
	}
}

void task3()
{
	while(1){
		// Task1 Code
	}
}

int main(void)
{
	MYRTOS_errorID Error = NO_ERROR;
	// HW_Init	(Initialize clockTree, ResetController)
	HW_Init();

	if(MYRTOS_Init() != NO_ERROR)
		while(1);


	// Create tasks
	Task1.Stack_Size = 1024;   // 1kByte
	Task1.P_TaskEntry = task1;
	Task1.Priority = 3;
	strcpy(Task1.TaskName, "task_1");

	Task2.Stack_Size = 1024;   // 1kByte
	Task2.P_TaskEntry = task2;
	Task2.Priority = 3;
	strcpy(Task2.TaskName, "task_2");

	Task3.Stack_Size = 1024;   // 1kByte
	Task3.P_TaskEntry = task3;
	Task3.Priority = 3;
	strcpy(Task3.TaskName, "task_3");

	Error += MYRTOS_Create_Task(&Task1);
	Error += MYRTOS_Create_Task(&Task2);
	Error += MYRTOS_Create_Task(&Task3);



	while(1)
	{



	}
}



