/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "FreeRTOS.h"
#include "Stm32_F103C6_gpio_driver.h"
#include "task.h"


TaskHandle_t TaskBlinkLEDHandle = NULL;    // Task will be accessed through this handle


/* Tasks prototypes */
void TaskBlinkLEDHandler(void *params);


void HW_Init(void)
{
	GPIO_PinConfig_t Pin13Cfg;
	Pin13Cfg.GPIO_PinNumber = GPIO_PIN_13;
	Pin13Cfg.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL;
	Pin13Cfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10MHZ;

	MCAL_GPIO_Init(GPIOC, &Pin13Cfg);
}

int main(void)
{
	RCC_GPIOC_CLK_EN();
	HW_Init();


//	BaseType_t xTaskCreate(    TaskFunction_t pvTaskCode,
//	                            const char * const pcName,
//	                            configSTACK_DEPTH_TYPE usStackDepth,
//	                            void *pvParameters,
//	                            UBaseType_t uxPriority,
//	                            TaskHandle_t *pxCreatedTask
//	                          );

	// Stack depth in words


	// Tasks creation
	xTaskCreate(TaskBlinkLEDHandler, "BlinkLEDTask", 128, NULL, 1, &TaskBlinkLEDHandle);


	// Start Scheduler
	vTaskStartScheduler();

    /* Loop forever */
	while(1)
	{

	}


	return 0;
}

//
/* Tasks handlers */
void TaskBlinkLEDHandler(void *params)
{
	while(1)
	{
		MCAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_LOW);
		vTaskDelay(50);
		MCAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_HIGH);
		vTaskDelay(50);
	}
}
