/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_EXTI_driver.h"
#include "Stm32_F103C6_USART_driver.h"
#include "stm32f103c6.h"
#include "Lcd.h"
#include "KPD_interface.h"


unsigned char ch;


void OUR_UART_IRQ_CallBack(void)
{
	MCAL_UART_ReceiveData(USART1, &ch, Disable);
	MCAL_UART_SendData(USART1, &ch, Enable);
}



int main(void)
{
	// Enable clock
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	// Polling Mechanism


//	UART_Config UartCfg;
//	UartCfg.BaudRate = UART_BaudRate_115200;
//	UartCfg.HWFlowCtrl = UART_HWFlowCtrl_NONE;
//	UartCfg.IRQ_Enable = UART_IRQ_Enable_NONE;
//	UartCfg.P_IRQ_CallBack = NULL;
//	UartCfg.Payload_length = UART_Payload_Length_8B;
//	UartCfg.Parity = UART_Parity_NONE;
//	UartCfg.StopBits = UART_StopBits_1;
//	UartCfg.USART_Mode = UART_Mode_Tx_Rx;


	// Using Interrupt

	UART_Config UartCfg;
	UartCfg.BaudRate = UART_BaudRate_115200;
	UartCfg.HWFlowCtrl = UART_HWFlowCtrl_NONE;

	UartCfg.IRQ_Enable = UART_IRQ_Enable_RXNE;

	UartCfg.P_IRQ_CallBack = OUR_UART_IRQ_CallBack;

	UartCfg.Payload_length = UART_Payload_Length_8B;
	UartCfg.Parity = UART_Parity_NONE;
	UartCfg.StopBits = UART_StopBits_1;
	UartCfg.USART_Mode = UART_Mode_Tx_Rx;

	MCAL_UART_Init(USART1, &UartCfg);
	MCAL_UART_GPIO_SetPins(USART1);

	while(1)
	{
//		MCAL_UART_ReceiveData(USART1, &ch, Enable);
//		MCAL_UART_SendData(USART1, &ch, Enable);

	}
}



