/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


// #define MCU_Act_As_Master
#define MCU_Act_As_Master

#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_EXTI_driver.h"
#include "Stm32_F103C6_USART_driver.h"
#include "Stm32_F103C6_SPI_driver.h"
#include "stm32f103c6.h"
#include "Lcd.h"
#include "KPD_interface.h"


unsigned char ch;


void OUR_SPI_IRQ_CallBack(struct S_IRQ_SRC irq_src)
{
	// Once you receive you go to the UART


#ifdef MCU_Act_As_Slave
	if(irq_src.RXNE)
	{
		ch = 0xf;
		MCAL_SPI_TX_RX(SPI1, &ch, Polling_Disable);
		MCAL_UART_SendData(USART1, &ch, Enable);
	}
#endif

}

void OUR_UART_IRQ_CallBack(void)
{

#ifdef MCU_Act_As_Master
	MCAL_UART_ReceiveData(USART1, &ch, Disable);
	MCAL_UART_SendData(USART1, &ch, Enable);
	// Send to SPI
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_LOW);
	MCAL_SPI_TX_RX(SPI1, &ch, Polling_Enable);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_HIGH);
#endif

}



int main(void)
{
	// Enable clock
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	// UART Initialization

	UART_Config UartCfg;
	UartCfg.BaudRate = UART_BaudRate_115200;
	UartCfg.HWFlowCtrl = UART_HWFlowCtrl_NONE;

	UartCfg.IRQ_Enable = UART_IRQ_Enable_RXNE;

	UartCfg.P_IRQ_CallBack = OUR_UART_IRQ_CallBack;

	UartCfg.Payload_length = UART_Payload_Length_8B;
	UartCfg.Parity = UART_Parity_NONE;
	UartCfg.StopBits = UART_StopBits_1;
	UartCfg.USART_Mode = UART_Mode_Tx_Rx;

	MCAL_UART_Init(USART1, &UartCfg);
	MCAL_UART_GPIO_SetPins(USART1);



	// SPI Initialization


	// Common Configurations
	SPI_Config SPI_Cfg;
	SPI_Cfg.CLKPhase = SPI_Clock_Phase_SECOND_EDGE;
	SPI_Cfg.CLKPolarity = SPI_Clock_Polarity_IDLE_HIGH;
	SPI_Cfg.DataSize = SPI_Data_Size_8BIT;
	SPI_Cfg.Frame_Format = SPI_Frame_Format_MSBFIRST;
	// Assume by default PCLK2 = 8MHz
	SPI_Cfg.Baudrate_Prescalar = SPI_Baudrate_Prescalar_8;
	SPI_Cfg.Communication_Mode = SPI_Communication_Mode_2LINES;


#ifdef MCU_Act_As_Master
	SPI_Cfg.Device_Mode = SPI_Device_Mode_Master;
	SPI_Cfg.IRQ_Enable = SPI_IRQ_NONE;
	SPI_Cfg.NSS = SPI_NSS_InternalSlaveSelect_Set;    // To use a gpio as a slave select and I'm the one who controls it
	SPI_Cfg.P_IRQ_CallBack = NULL;


	// Configure SS on PORTA PIN4 by GPIO
	// output enabled Alternate function push-pull


	GPIO_PinConfig_t GPIO_Cfg;
	GPIO_Cfg.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL;
	GPIO_Cfg.GPIO_PinNumber = GPIO_PIN_4;
	GPIO_Cfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10MHZ;
	MCAL_GPIO_Init(GPIOA, &GPIO_Cfg);


	// Force the slave select to be high (idle mode)
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_HIGH);


#endif


#ifdef 	MCU_Act_As_Slave
	SPI_Cfg.Device_Mode = SPI_Device_Mode_Slave;
	SPI_Cfg.IRQ_Enable = SPI_IRQ_RXNEIE;
	SPI_Cfg.NSS = SPI_NSS_HW_SLAVE;
	SPI_Cfg.P_IRQ_CallBack = OUR_SPI_IRQ_CallBack;
#endif

	MCAL_SPI_Init(SPI1, &SPI_Cfg);
	MCAL_SPI_GPIO_Set_Pins(SPI1);



	while(1)
	{
	}
}



