/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103C6_gpio_driver.h"
#include "stm32f103c6.h"

void clock_init()
{
	// Enable clock for GPIOA (bit 2)
	RCC_GPIOA_CLK_EN();
	// Enable clock for GPIOB (bit 3)
	RCC_GPIOB_CLK_EN();

}

void GPIO_init()
{

	GPIO_PinConfig_t PinCfg;

	// PA1 input High Z (Floating)
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLOATING;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	// PB1 output push pull mode
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL;
	PinCfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10MHZ;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	// PA13 input High Z (Floating)
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLOATING;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	// PB13 output push pull mode
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL;
	PinCfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10MHZ;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

}


void wait_ms(uint32_t time){
	uint32_t i,j;
	for(i=0;i<time;i++)
		for(j=0;j<255;j++);
}


int main(void)
{
	clock_init();
	GPIO_init();

	while(1)
	{
		// PA1 >> Connected to external pull up resistance
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0){  // Press
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0);   // Single Press (As long as the user still pressing, stuck here)
		}

		// PA13 >> Connected to external pull down resistance
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1){  // Multiple Pressing
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		}
		wait_ms(1);
	}
}



